name: Generate 3D Profile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        with:
          username: r0bince
        env:
          USERNAME: r0bince
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Update 3D graph"
          git push




 # Generate Summary Cards
      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: r0bince

      - name: Commit Summary Cards
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-summary-card-output/
          git diff-index --quiet HEAD || git commit -m "Update summary cards"
          git push

